/*
 * Spinnaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gate

type User struct {
	AccountNonExpired     bool               `json:"accountNonExpired,omitempty"`
	AccountNonLocked      bool               `json:"accountNonLocked,omitempty"`
	AllowedAccounts       []string           `json:"allowedAccounts,omitempty"`
	Authorities           []GrantedAuthority `json:"authorities,omitempty"`
	CredentialsNonExpired bool               `json:"credentialsNonExpired,omitempty"`
	Email                 string             `json:"email,omitempty"`
	Enabled               bool               `json:"enabled,omitempty"`
	FirstName             string             `json:"firstName,omitempty"`
	LastName              string             `json:"lastName,omitempty"`
	Roles                 []string           `json:"roles,omitempty"`
	Username              string             `json:"username,omitempty"`
}
