/*
 * Spinnaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gate

type Account struct {
	AccountId               string              `json:"accountId,omitempty"`
	Name                    string              `json:"name,omitempty"`
	Permissions             map[string][]string `json:"permissions,omitempty"`
	ProviderVersion         string              `json:"providerVersion,omitempty"`
	RequiredGroupMembership []string            `json:"requiredGroupMembership,omitempty"`
	Skin                    string              `json:"skin,omitempty"`
	Type                    string              `json:"type,omitempty"`
}
