[metadata]
  package = "github.com/zchee/spinctl"

required = []

ignored = []

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "go.uber.org/zap"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/fatih/color"
  branch = "master"

[[constraint]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[constraint]]
  name = "github.com/json-iterator/go"
  branch = "master"

[[constraint]]
  name = "github.com/zchee/go-open"
  version = "1.0.0"

[[override]]
  name = "go.uber.org/multierr"
  branch = "master"

[[override]]
  name = "github.com/modern-go/concurrent"
  branch = "master"

[[override]]
  name = "github.com/modern-go/reflect2"
  branch = "master"
