[metadata]
  package = "github.com/zchee/spinctl"

required = []
ignored = []

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"
