version: 2.1

orbs:
  golang: cci-orb/golang@dev:v0.0.1

defaults: &defaults
  working_directory: /go/src/github.com/zchee/spinctl
  executor: golang/stretch
  environment:
    GO111MODULE: "on"
  shell: /bin/bash -euo pipefail

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Test and collect coverages
          command: |
            make coverage/junit
      - run:
          name: Upload coverages to codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

  lint:
    <<: *defaults
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Run lint for sources
          command: |
            make lint

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - lint:
          context: org-global
