/*
 * Kayenta API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kayenta

import (
	"time"
)

type Execution struct {

	Application string `json:"application,omitempty"`

	Authentication *AuthenticationDetails `json:"authentication,omitempty"`

	BuildTime int64 `json:"buildTime,omitempty"`

	Canceled bool `json:"canceled,omitempty"`

	CanceledBy string `json:"canceledBy,omitempty"`

	CancellationReason string `json:"cancellationReason,omitempty"`

	Description string `json:"description,omitempty"`

	EndTime int64 `json:"endTime,omitempty"`

	Id string `json:"id,omitempty"`

	InitialConfig map[string]Serializable `json:"initialConfig,omitempty"`

	KeepWaitingPipelines bool `json:"keepWaitingPipelines,omitempty"`

	LimitConcurrent bool `json:"limitConcurrent,omitempty"`

	Name string `json:"name,omitempty"`

	Notifications []Mapstringobject `json:"notifications,omitempty"`

	Origin string `json:"origin,omitempty"`

	Paused *PausedDetails `json:"paused,omitempty"`

	PipelineConfigId string `json:"pipelineConfigId,omitempty"`

	Stages []Stage `json:"stages,omitempty"`

	StartTime int64 `json:"startTime,omitempty"`

	StartTimeTtl time.Time `json:"startTimeTtl,omitempty"`

	Status string `json:"status,omitempty"`

	Trigger *Trigger `json:"trigger,omitempty"`

	Type_ string `json:"type,omitempty"`
}
