/*
 * Kayenta API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kayenta

type Trigger struct {

	Artifacts []Artifact `json:"artifacts,omitempty"`

	CorrelationId string `json:"correlationId,omitempty"`

	DryRun bool `json:"dryRun,omitempty"`

	Notifications []Mapstringobject `json:"notifications,omitempty"`

	Parameters *interface{} `json:"parameters,omitempty"`

	Rebake bool `json:"rebake,omitempty"`

	ResolvedExpectedArtifacts []ExpectedArtifact `json:"resolvedExpectedArtifacts,omitempty"`

	Strategy bool `json:"strategy,omitempty"`

	Type_ string `json:"type,omitempty"`

	User string `json:"user,omitempty"`
}
