/*
 * Spinnaker Front50 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package front50

type Project struct {

	Config *ProjectConfig `json:"config,omitempty"`

	CreateTs int64 `json:"createTs,omitempty"`

	Email string `json:"email,omitempty"`

	Id string `json:"id,omitempty"`

	LastModifiedBy string `json:"lastModifiedBy,omitempty"`

	MetaClass *MetaClass `json:"metaClass,omitempty"`

	Name string `json:"name,omitempty"`

	UpdateTs int64 `json:"updateTs,omitempty"`
}
