/*
 * clouddriver
 *
 * Cloud read and write operations
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddriver

type InstanceCounts struct {

	Down int32 `json:"down,omitempty"`

	OutOfService int32 `json:"outOfService,omitempty"`

	Starting int32 `json:"starting,omitempty"`

	Total int32 `json:"total,omitempty"`

	Unknown int32 `json:"unknown,omitempty"`

	Up int32 `json:"up,omitempty"`
}
