/*
 * clouddriver
 *
 * Cloud read and write operations
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddriver

type LoadBalancerInstance struct {

	Health *interface{} `json:"health,omitempty"`

	Id string `json:"id,omitempty"`

	Zone string `json:"zone,omitempty"`
}
