/*
 * clouddriver
 *
 * Cloud read and write operations
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddriver

type SecurityGroup struct {

	AccountName string `json:"accountName,omitempty"`

	Application string `json:"application,omitempty"`

	CloudProvider string `json:"cloudProvider,omitempty"`

	Id string `json:"id,omitempty"`

	InboundRules []Rule `json:"inboundRules,omitempty"`

	Moniker *Moniker `json:"moniker,omitempty"`

	Name string `json:"name,omitempty"`

	OutboundRules []Rule `json:"outboundRules,omitempty"`

	Region string `json:"region,omitempty"`

	Summary *SecurityGroupSummary `json:"summary,omitempty"`

	Type_ string `json:"type,omitempty"`
}
