/*
 * clouddriver
 *
 * Cloud read and write operations
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddriver

type ServerGroupManager struct {

	Account string `json:"account,omitempty"`

	Moniker *Moniker `json:"moniker,omitempty"`

	Name string `json:"name,omitempty"`

	Region string `json:"region,omitempty"`

	ServerGroups []ServerGroupSummary `json:"serverGroups,omitempty"`
}
