/*
 * clouddriver
 *
 * Cloud read and write operations
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddriver

type Subnet struct {

	Id string `json:"id,omitempty"`

	Purpose string `json:"purpose,omitempty"`

	Type_ string `json:"type,omitempty"`
}
